language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# Configure git and add ssh keys
before_install:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - mkdir -p ~/.ssh
  - echo "$SSH_ID_RSA" > ~/.ssh/id_rsa
  - echo "$SSH_ID_RSA_PUB" > ~/.ssh/id_rsa.pub
# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# Run the tests
script:
  coverage run --source=scriptcore setup.py test
# Trigger coverall
after_success:
  - coveralls
  - python setup.py docs_publish

# Notifications
notifications:
  slack:
    rooms:
      - secure: aN99+PXy3x95XznRjAdVkibe13qZkhTgu7uqEB5WbL1qr542aoxkbgQy06wQ+luDpwmAk6fql2lblS7DyZrN152lCYwidOGlhBg6alECgNEE51f7KuuDubQyq6zKqxDuniUOkkwq1jXtDOADuJwxOMHQncsIcnFlqKh8GMCJ4EXaVv+zTkW/Fsut4o3+5hi1RFtamK4qdGAhljfGqM09i/CVr264sL5pUQ0kfS3Z49tgM7ybNi5lq7GJ42Ei9v9ZnUidNDPGNaTs9nQWCiMMQyDKakek0d4xWgi3VlkL+FF9R4nh5bcx8kPRW57uYWRcJJFYxfeKohLYTqzDqHCPzFVGz720TETLH0B172Wxl4ldWUMBYbq73EpuGyYfmfsfxr+5nPLMZrxgva18Du3JmFVNkZu+ggJhsmGMrOZwEIM+BAYjh9KSF7RD5Zw2RnLFep2pCzBroBa9rLF8VH+g91c4lO7V7xgY9Ka38jr4UfdfKPWzSnq3OaVoo6pWqYkLZHPR/s16C2HxxVgQaJeiANBArDXdRjhTXt0w0ApC8OIs7WmkaIM+sJ56k5QWeJoYhaPzykZsNZKKThyRY5dUAMpcV0czSY5TuOSz1cTRobT+09e2tood1We/hdCXEbY1awbOLAOJoGjWHD4I88JTqWJ1VOsd7lnUPkNSMQFWzQ4=
    on_success: change
    on_failure: always
  email: false
