language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# Run the tests
script:
  coverage run --source=scriptcore setup.py test
# Trigger coverall
after_success:
  coveralls

# Notifications
notifications:
  slack:
    rooms:
      - secure: qSmLLoQ3qPHBJ5miNvcVwCBGo2oJz+O5xLgIOrIbVY3NIWJityJW/l2dkKvd94kI7XOssPDDSWUUNUinxwqttaB+UvhIy0in2Tdu80IwXYI0AmVLaflfsTUuREN6nPj4MXxrZNwggRqUaOmRQYUKOVrt6WjZtw/0/qxR/xofx02nr2SubI2Ac7d5H+fBTNyAmt41cjsY1kTuUyLSA2JMub9hh7No344GkRddoIOc6yW2beSAuFtZc+xYUb92rwujWksAoVowSqpF/PNK+CYbzK9cxU4mxu8/ZpnwNQFoJqyHRfGzLtFN9eIW+A99LliAmpRdnXxjTSRulQgb7j5DY+me0p4/1gqn1x4uMjlb3GfRfDc6CEywd0sslBMWh72nW2YkmjvVqnALCVmlDlMu5pI8aA8Vu4JrKm+plajCCIv+jEbSgJAPZQS2v5Tk8ddVaBEc13epLLPKZn405ZQJn738mR2669sqkWE+otPSTuWBE8xk6EcdGMQ+Lr5yrEBn6F4HWkTGA/j7wAUAEmtCjBBSjs8L4vSIU4h0C8ozJT3GA/sBUB4ue/5RtUwRmNXIpGmP8BVA2soX7uk8Eu58BhfiUVnFxYwQVPQb7fHpfWH/xb5jk6TVFZE75sG4Moylm/RhNGCVYKwS5B+rW2sMTPBXuuHoDH0oyUw8qcNNuU8=
    on_success: change
    on_failure: always
  email: false
